define([], function () {
	return {
		// Library Strings
		ErrorLstName: 'IK-ErrorLogs',
		ErrorLogLstDesc: 'List to hold all the component errors in the Intranet-Kit package.',
		EL_FldTitle: 'Title',
		EL_FldMessage: 'Message',
		EL_FldStack: 'Stack',

		SettingsLstName: 'IK-Settings',
		SettingsLstDesc: 'List to hold all the settings for the Intranet-Kit components.',
		SL_FldTitle: 'Title',
		SL_FldConVal: 'ConfigValue',
		SL_FldDesc: 'Description',
		SL_FldCat: 'Category',

		LaunchPadGlobalLstDesc: 'List to store global links that are common to multiple users.',
		LaunchPadUserLstDesc: 'List to store personal links based on the user.',
		Fld_LP_Url: 'URL',
		Fld_LP_Icon: 'IconName',
        Fld_LP_Image: 'IconImage',
		Fld_LP_Window: 'NewWindow',

		Fld_Created: 'Created',
		Fld_Author: 'Author',
		Fld_Modified: 'Modified',
		Fld_Editor: 'Editor',
		VW_AllItems: 'All Items',
		Fld_IsActive: 'IsActive',
		Fld_Sequence: 'Sequence',
		Fld_News: 'IsNews',
        Fld_Desc: 'Description',

        Fld_News_CI: 'CoverImage',
        Fld_News_Desc: 'Description',
        Fld_News_Cont: 'NewsContent',

		// Common Stings
		Btn_Create: 'Create',
		Btn_Cancel: 'Cancel',
        Btn_Save: "Save",
		CloseAL: "Close",
        Btn_ChooseList: 'Add to collection',
        Btn_Verify: 'Verify',
        Btn_BackToList: 'Back to List(s) Selection',
        Btn_BackToSite: 'Back to Site(s) Selection',
		Btn_Back: 'Back',

        WP_GN_Gen: 'General Settings',
        WP_L_Title: 'Title',
        WP_PH_Title: 'Title...',
        WP_L_LayOpt: 'Layout options',
        WP_L_LO_Tile: 'Tiles',
        WP_L_LO_Button: 'Buttons',
        WP_L_LO_Comp: 'Compact',
        WP_L_LO_Grid: 'Grid',
        WP_L_TileSize: 'Tile Size',
        WP_TS_S: 'Small',
        WP_TS_M: 'Medium',
        WP_TS_L: 'Large',
        WP_TS_XL: 'Extra Large',

		LicDialogTitle: 'License details',
		SettingsDialogTitle: 'Settings',
		Desc_License: "Intranet Kit license info. Do not change or delete which makes the app not to work.",
		LicNotConfigured: 'Oops! It looks like the license is not configured.',
		LicExpired: 'Oops! It looks like the license expired.',
		LicLink: 'Configure License',
		Invalid_LicKey: 'Invalid license key',
		App_Act_Error: 'Something wrong while activating the app!',
		Desc_AppWeb: 'Required while activating or changing the license key or contact info.',

        Msg_LoadingLists: "Loading Lists...",
		Msg_Loading: 'Loading...',
		Msg_Wait: 'Please wait...',
		Msg_Mandatory: 'Please fill in the mandatory fields!',
		Msg_SameList: "List names should be different!",
		Msg_LicSPAdminInfo: 'The License can only be updated by SharePoint Administrator for the entire tenant or by Site Administrator for the site.',		
		Msg_ConfigHeader: 'Configuration missing',
		Msg_Config_CreateList: 'Create lists for storing the Launch Pad links.',		
		Msg_Config_WPProp_Read: 'Configure the web part properties. Please edit the page to update the web part properties.',
		Msg_Config_WPProp_Edit: 'Configure the web part properties.',
        Msg_InvalidURL: "Invalid URL!",
        Msg_SaveSuccess: "Saved sucessfully!",
        Msg_ReqImage: 'Please select an image!',
		Msg_NoData: 'Sorry, no data found!',

		Lbl_CreateLists: 'Create List(s)',
		Lbl_Config_WPProp: 'Configure Properties',

        
        NS_DialogTitle: 'News list settings',
        Msg_LoadingSiteColl: "Loading Site collections...",
        Title_SitesContainer: "Select a Team or site",
        Title_ListContainerBC: "Choose a list from",
        ListContainer_NoListDesc1: "This site doesn't have compatible lists",
        ListContainer_NoListDesc2: "Select another site to find lists",
        ListContainer_BCDesc: "Choose the site to load the compatible lists!",
	}
});