define([], function () {
    return {
        "PropertyPaneDescription": "Description",
        "BasicGroupName": "Group Name",
        "DescriptionFieldLabel": "Description Field",
        "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
        "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
        "AppSharePointEnvironment": "The app is running on SharePoint page",
        "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",

        Settings_Dialog_Note: 'Create a global and user links list with the name of your choice and map it in the web part properties.',
        Settings_GTL: 'Select Global Links List',
        Settings_Cache_GT: 'Fast loading for Global Links',
        Settings_Cache_GT_Desc: 'Will use caching mechanism to load the content faster from the local cache.',
        Settings_EN_UserTile: 'Enable Users to add own tile',
        Settings_UTL: 'Select User Links List',
        Settings_Cache_UT: 'Fast loading for My Links',
        Settings_Cache_UT_Desc: 'Will use caching mechanism to load the content faster from the local cache.',
        Settings_UT_Limit: 'My Links Count',
        Settings_Man_Title: 'Enable Manage Links',
        Settings_Man_UTile: 'Manage Links',

        DeleteDialogDescription: "Are you sure, you would like to delete the link?",
        DeleteDialogSDNote: "Deleted link(s) can be restored from the 'Manage Links' section.",
        DeleteDialogNote: "Deleted link(s) can't be restored.",
        ItemsLimitAdd: "Sorry, you have reached the limit. No more links can be added",
        Allowed20Chars: "Maximum of 20 characters are allowed...",
        Allowed30Chars: "Maximum of 30 characters are allowed...",

        LicDialogTitle: 'License details',
		SettingsDialogTitle: 'Settings',
		Desc_License: "Modern Quicklinks license info. Do not change or delete which makes the app not to work.",
		LicNotConfigured: 'Oops! It looks like the license is not configured.',
		LicExpired: 'Oops! It looks like the license expired.',
		LicLink: 'Configure License',
		Invalid_LicKey: 'Invalid license key',
		App_Act_Error: 'Something wrong while activating the app!',
		Desc_AppWeb: 'Required while activating or changing the license key or contact info.',

        ErrorLstName: 'IK-ErrorLogs',
		ErrorLogLstDesc: 'List to hold all the component errors in the Intranet-Kit package.',
		EL_FldTitle: 'Title',
		EL_FldMessage: 'Message',
		EL_FldStack: 'Stack',

        SettingsLstName: 'IK-Settings',
		SettingsLstDesc: 'List to hold all the settings for the Intranet-Kit components.',
		SL_FldTitle: 'Title',
		SL_FldConVal: 'ConfigValue',
		SL_FldDesc: 'Description',
		SL_FldCat: 'Category',

		LaunchPadGlobalLstDesc: 'List to store global links that are common to multiple users.',
		LaunchPadUserLstDesc: 'List to store personal links based on the user.',
		Fld_LP_Url: 'URL',
		Fld_LP_Icon: 'IconName',
        Fld_LP_Image: 'IconImage',
		Fld_LP_Window: 'NewWindow',
        Fld_LP_Desc: 'Description',

		Fld_Created: 'Created',
		Fld_Author: 'Author',
		Fld_Modified: 'Modified',
		Fld_Editor: 'Editor',
		VW_AllItems: 'All Items',
		Fld_IsActive: 'IsActive',
		Fld_Sequence: 'Sequence',

        Fld_lbl_Title: 'Title',
        Fld_lbl_Url: 'URL',
        Fld_lbl_Desc: 'Description',
        Fld_lbl_NewWin: 'Open link in New Window?',
        Fld_lbl_IcoImg: 'Icon or Image?',
        Fld_lbl_Icon: 'Icon',
        Fld_lbl_Img: 'Image',
        Fld_lbl_Seq: 'Sequence',

        WP_GN_Gen: 'General Settings',
        WP_GN_Layout: 'Layout Settings',
        WP_GN_LstSett: 'List Settings',
        WP_GN_Color: 'Color Settings',
        WP_L_Title: 'Title',
        WP_PH_Title: 'Title...',
        WP_L_STitle: 'Show / Hide Title',
        WP_L_HeaderIco: 'Title Icon',
        WP_Btn_HeaderIco: 'Select',
        WP_L_LayOpt: 'Layout options',
        WP_L_LO_Tile: 'Tiles',
        WP_L_LO_Button: 'Buttons',
        WP_L_LO_Comp: 'Compact',
        WP_L_LO_Grid: 'Card',
        WP_L_TileSize: 'Tile Size',
        WP_TS_S: 'Small',
        WP_TS_M: 'Medium',
        WP_TS_L: 'Large',
        WP_TS_XL: 'Extra Large',
        WP_T_S: 'Show',
        WP_T_H: 'Hide',
        WP_S_Asc: 'Ascending',
        WP_S_Desc: 'Descending',
        WP_GL_VAL_NOTSEL: 'Please select a list',
        WP_UL_VAL_NOTSEL: 'Please select a list',
        WP_GL_Info: 'Enable Information Icon',
        WP_GL_InfoDesc: `Enabling this option will display an Info icon on each link. Clicking on the icon will display a panel with the detailed description of the tile. Make sure the 'Description' (Muliti-line text - RichText enabled) field is added to the global links list.`,
        WP_Srch_Enable: 'Enable Search',
        WP_Srch_Placeholder: 'Search Placeholder',
        WP_Srch_PlaceholderPH: 'Search...',
        WP_Srch_ContentEnable: 'Show Search on top of Content Area',
        WP_Srch_Content_Info: `Enabling this option will display a search box on top of the content area.`,
        WP_Srch_Width_Label: 'Width (px)',
        WP_Srch_Width_Desc: 'Width is configured in px. Enter only number.',
        WP_Srch_KWEnable: 'Enable Keyword Search',
        WP_SO_Label: 'Sort Order',
        WP_MT_Desc: `Title should be enabled to use Manage Tiles`,
        WP_KW_Desc: 'Keyword search is applicable only for the global list. To enable keyword search, please provide the internal name of the field that is added to the global links list with the Multiline text field type.',
        WP_KW_Field: 'Keyword Search Field',
        WP_KW_FieldPH: 'Enter the field internal name',

        Msg_LoadingLists: "Loading Lists...",
		Msg_Loading: 'Loading...',
		Msg_Wait: 'Please wait...',
		Msg_Mandatory: 'Please fill in the mandatory fields!',
        Msg_ListReq: 'Please give a list name for Global or User Links',
		Msg_SameList: "List names should be different!",
		Msg_LicSPAdminInfo: 'The License can only be updated by SharePoint Administrator for the entire tenant or by Site Administrator for the site.',		
		Msg_ConfigHeader: 'Configuration missing',
		Msg_Config_CreateList: 'Create lists for storing the Launch Pad links.',		
		Msg_Config_WPProp_Read: 'Configure the web part properties. Please edit the page to update the web part properties.',
		Msg_Config_WPProp_Edit: 'Configure the web part properties.',
        Msg_InvalidURL: "Invalid URL!",
        Msg_SaveSuccess: "Saved sucessfully!",
        Msg_ReqImage: 'Please select an image!',
		Msg_NoData: 'Sorry, no data found!',

        Lbl_CreateLists: 'Create List(s)',
		Lbl_Config_WPProp: 'Configure Properties',

        
        NS_DialogTitle: 'News list settings',
        Msg_LoadingSiteColl: "Loading Site collections...",
        Title_SitesContainer: "Select a Team or site",
        Title_ListContainerBC: "Choose a list from",
        ListContainer_NoListDesc1: "This site doesn't have compatible lists",
        ListContainer_NoListDesc2: "Select another site to find lists",
        ListContainer_BCDesc: "Choose the site to load the compatible lists!",

        Btn_Create: 'Create',
		Btn_Cancel: 'Cancel',
        Btn_Save: "Save",
		CloseAL: "Close",
        Btn_ChooseList: 'Add to collection',
        Btn_Verify: 'Verify',
        Btn_BackToList: 'Back to List(s) Selection',
        Btn_BackToSite: 'Back to Site(s) Selection',
		Btn_Back: 'Back',

        HDR_Add: 'Add New Link',
        HDR_Edit: 'Edit Link',
        HDR_List: 'My Links'
    }
});